# Generated by Django 5.0.4 on 2024-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_category_alter_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default=None),
        ),
    ]
